---
SERVER_HOSTNAME: quay.apps-crc.testing
SETUP_COMPLETE: true
TAG_EXPIRATION_OPTIONS:
    - 0s
    - 1d
    - 1w
    - 2w
    - 4w
    - 3y
DISTRIBUTED_STORAGE_CONFIG:
  local_us:
  - RadosGWStorage
  - access_key: IkxV4HZcWpA8S9uZQ6aW
    bucket_name: quay
    hostname: 192.168.91.136:9000
    is_secure: false
    secret_key: mE3pwW8uD5olvInf8ZWEjUrByn3mHD4vuc3FG8Y3
    storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
- local_us
DISTRIBUTED_STORAGE_PREFERENCE:
- local_us
PREFERRED_URL_SCHEME: http
---

## access & secert key generate from minio/s3 stroage
## hostname is the path of minio/s3 stroage UI path

---
oc create secret generic --from-file config.yaml=./config.yaml config-bundle-secret -n <project-name> #run after created the config.yaml
---

#if the server is down, need to clean the old file and recreate the bucket if you rebuild
