SERVER_HOSTNAME: quay.apps-crc.testing
SETUP_COMPLETE: true
TAG_EXPIRATION_OPTIONS:
    - 0s
    - 1d
    - 1w
    - 2w
    - 4w
    - 3y
DISTRIBUTED_STORAGE_CONFIG:
  local_us:
  - RadosGWStorage
  - access_key: 4Vf4rKnYdPw1CQNKjf79 ##generate from minio access key, please clean up ## before deploy
    bucket_name: quay ##the bucket name which create from minio
    hostname: 172.17.0.2 ##minio stroage UI host, please clean up ## before deploy
    is_secure: false
    secret_key: aYEnstm0jzTzO61UnWS5h1Qs8nTAJ5HBKjdCHMdb ##generate from minio secert key, please clean ## before deploy
    storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
- local_us
DISTRIBUTED_STORAGE_PREFERENCE:
- local_us
PREFERRED_URL_SCHEME: http


oc create secret generic --from-file config.yaml=./config.yaml config-bundle-secret -n <project-name> #run after created the config.yaml
